### ISSUE TITLE
[Create Wallet] Phone number field is  no longer needed on create wallet.

### ISSUE THREAD

**Issue by salonigoel24** [klubcoin/lcn-mobile#145]
![CreateWallet_PhoneNumber_Skype](https://user-images.githubusercontent.com/98397235/157365529-56e861f3-3b72-45f0-91b3-ce1bd8a6cdd2.png)
As per discussion with Stephane, following changes are needed in create wallet 
1. We will move phone number to update profile screen. Need to be verified by OTP if user enters in update screen.
2 Create wallet changes -
---remove phone number
-- Move username to screen1
-- Only email OTP needed for wallet creation.

**Comment by jcalado-freelancersph** [comment]
### **Retested and verifying this issue as `PASSED`**

**Build Environment:** Dev Environment
**Affects Version:** 1.0.0.13
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

Remarks: Will transition this issue to "QA Done". **This issue is now ready to be deployed to Staging Environment.**

**Comment by TaiTrien** [comment]
Hi @jcalado-freelancersph, please check and close this ticket

**Comment by jcalado-freelancersph** [comment]
### **Retested and verifying this issue as `PASSED`**

**Build Environment:** Staging Environment
**Affects Version:** 1.0.0.14
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

Remarks: Will transition this issue to "`Done`" This issue is now ready to be deployed on Production.
