### ISSUE TITLE
[Wallet Transaction Management][Send Token via QR Code] Fix must have unrecognized QR Code validation handler for scanning QR Codes with domain URL on Send KLUB Token QR Scanner.

### ISSUE THREAD

**Issue by jkevincalado** [klubcoin/lcn-mobile#213]
### **Description:**
Must have unrecognized QR Code validation handler for scanning QR Codes with domain URL on Send KLUB Token QR Scanner.

**Build Environment:** Prod Candidate Environment
**Affects Version:** 1.0.0.prod.1
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

### **Pre-condition:**
1. User successfully installed the app
2. User has an existing wallet account
3. User is currently at Dashboard

### **Steps to Reproduce:** 
1. View Dashboard
4. Tap Hamburger Button
5. Tap Wallet Option
6. View Wallet Screen

### **Expected Result:** 
Display unrecognized QR Code message

### **Actual Result:** 
Klubcoin Application becoming browser app which is not recommended on Business Requirements

### **Attachment/s:** 
https://drive.google.com/file/d/1i-59b4FBsz_cZoAzox85mB9yjxRJI1uF/view

**Comment by johncalado** [comment]
### **Retested and verifying this issue as `FAILED`**

**Build Environment:** Prod Environment
**Affects Version:** 1.0.0.production.2
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

Remarks: Will transition this issue to "`Re-Open`"

Failing Criteria:
1. Scanning random QR Code with Domain URL does not return "Unrecognized QR Code" message.
2. Scanning Payment Request QR Code is also not recognized by the application QR Scanner. It does nothing instead of redirecting to Send Token Confirmation Screen.

**Comment by johncalado** [comment]
### **Retested and verifying this issue as `PASSED`**

**Build Environment:** Prod Environment
**Affects Version:** 1.0.0.production
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

Remarks: Will transition this issue to "`Done`"
