### ISSUE TITLE
[Tip] Send tip link page doesn't show buttons correctly

### ISSUE THREAD

**Issue by salonigoel24** [klubcoin/lcn-mobile#37]
![1645618316732](https://user-images.githubusercontent.com/98397235/155322248-a0f8fa86-ffc0-43db-b89a-b2b4f7bb65d1.JPEG)
**Description:**
Send tip link page doesn't show text of buttons correctly

Pre-requisite:
User is logged in on Klubcoin app.
Build Version: 1.0.0(8)

Steps to Reproduce:
Click on the hamburger button to open the drawer.
On the drawer, select receive tips.
Seelcts KLUb, enters value, and click Next.
Send tip link page doesn't show buttons correctly

Expected Result:
Send tip link page doesn't show buttons correctly as Copy to clipboard, and QR code

Actual Result:
Send tip link page doesn't show buttons correctly

**Comment by TaiTrien** [comment]
Hi @salonigoel24 and @jcalado-freelancersph, please check on next version (v.1.0.0+14(dev))

**Comment by jcalado-freelancersph** [comment]
### **Retested and verifying this issue as `PASSED`**

**Build Environment:** Staging Environment
**Affects Version:** 1.0.0.14
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

Remarks: Will transition this issue to "`Done`" This issue is now ready to be deployed on Production.
